version: 0.1

phases:
    build:
      commands:
        - npm install
        -npm test
      commands:
        - npm run webpack
artifacts:
  files:
    - index.html
    - react.html
    - favicon.ico
    - styles/*
    - images/*
    - dist/bundle.js
